[package]
name = "mucab"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8"
regex = "1"
glob = "0.3"
zeekstd = "0.6"

[[bin]]
name = "converter"
path = "src/bin/converter.rs"

[[bin]]
name = "mucab"
path = "src/bin/mucab.rs"

[lib]
path = "src/lib.rs"
